server:
  port: 8082

spring:
  profiles:
    active: dev
  application:
    name: MarketplaceService
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    drop-first: false
    change-log: db.changelog/db.changelog-master.xml
    default-schema: public
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect